ARG MYSQL_LOCAL_IMAGE_VERSION
FROM mysql:${MYSQL_LOCAL_IMAGE_VERSION:-5}

ARG MYSQL_LOCAL_IMAGE_VERSION
COPY ./config/mysql-${MYSQL_LOCAL_IMAGE_VERSION:-5}.cnf /etc/mysql/conf.d/local.cnf

EXPOSE 3306
